---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: defuse-frontend
  description: frontend for defuse
  tags:
    - website
  links:
    - url: https://near-intents.org
  annotations:
    aurora.dev/security-tier: "2"
spec:
  owner: defuse-team
  system: defuse-protocol
  type: website
  lifecycle: production
  dependsOn:
    - component:defuse-contract
