name: E2E UI automation tests worker

on:
  pull_request:
    types: [opened, synchronize, reopened]
  repository_dispatch:
    types: [vercel_deployment]
  workflow_call:
    inputs:
      tag:
        description: "Provide tag to run tests by"
        required: true
        type: string
      base_url:
        description: "Base URL for the application"
        required: false
        type: string
      manual_trigger:
        required: false
        type: boolean
        default: true
    secrets:
      MM_SEED_PHRASE:
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: "Provide tag to run tests by"
        required: true
        type: choice
        options:
          - "@near-intents-wallet"
          - "@near-intents-wallet-swapping"
          - "@near-intents-wallet-otc"
          - "@near-intents-wallet-deposit"
          - "@near-intents-wallet-withdraw"
      base_url:
        description: "Base URL for the application"
        required: false
        type: string
      manual_trigger:
        description: "Set to true to manually trigger the workflow"
        required: false
        type: boolean
        default: false

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    # runs-on: ubuntu-8-core
    timeout-minutes: 240

    env:
      MM_SEED_PHRASE: ${{ secrets.MM_SEED_PHRASE }}
      NEXT_PUBLIC_BASE_URL: ${{ inputs.base_url }}
      # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RUN_TAG: ${{ inputs.tag || '@near-intents-wallet' }}
      MANUAL_TRIGGER: ${{ inputs.manual_trigger }}
      EXTENSION_LOAD_TIMEOUT: 60000
      CHROME_ARGS: "--no-sandbox --disable-dev-shm-usage"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Jod

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install linux deps
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 2560x1440x24 -listen tcp -ac &
          fluxbox -display :0.0 &
        env:
          DISPLAY: :0.0

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright
        run: bunx playwright install chromium
      - name: Wait for Vercel Deployment
        if: ${{ github.event_name == 'pull_request' }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Waiting for Vercel deployment for PR #$PR_NUMBER..."

          # Debug token and project ID
          echo "VERCEL_TOKEN length: ${#VERCEL_TOKEN}"
          echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"
          echo "Token starts with: ${VERCEL_TOKEN:0:10}..."

          # Wait for deployment to be ready
          DEPLOYMENT_URL=""
          MAX_ATTEMPTS=120  # 20 minutes max wait
          ATTEMPT=0

          while [ -z "$DEPLOYMENT_URL" ] && [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            ATTEMPT=$((ATTEMPT + 1))
            echo "Attempt $ATTEMPT/$MAX_ATTEMPTS: Checking for deployment..."

            # Query Vercel API for deployments associated with this PR
            RESPONSE=$(curl -s -G "https://api.vercel.com/v6/deployments" \
              -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
              --data-urlencode "projectId=${{ secrets.VERCEL_PROJECT_ID }}" \
              --data-urlencode "meta.githubPullRequestId=$PR_NUMBER" \
              --data-urlencode "state=READY" \
              --data-urlencode "limit=1")

            echo "API Response (READY): $RESPONSE"
            DEPLOYMENT_URL=$(echo "$RESPONSE" | jq -r '.deployments[0].url // empty')
            echo "Extracted URL (READY): $DEPLOYMENT_URL"

            # If no READY deployment found, try without state filter
            if [ -z "$DEPLOYMENT_URL" ]; then
              echo "No READY deployment found, checking all deployments..."
              RESPONSE_ALL=$(curl -s -G "https://api.vercel.com/v6/deployments" \
                -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
                --data-urlencode "projectId=${{ secrets.VERCEL_PROJECT_ID }}" \
                --data-urlencode "meta.githubPullRequestId=$PR_NUMBER" \
                --data-urlencode "limit=5")

              echo "API Response (ALL): $RESPONSE_ALL"
              DEPLOYMENT_URL=$(echo "$RESPONSE_ALL" | jq -r '.deployments[0].url // empty')
              DEPLOYMENT_STATE=$(echo "$RESPONSE_ALL" | jq -r '.deployments[0].state // empty')
              echo "Extracted URL (ALL): $DEPLOYMENT_URL"
              echo "Deployment State: $DEPLOYMENT_STATE"
            fi

            if [ -n "$DEPLOYMENT_URL" ]; then
              echo "✅ Vercel deployment is ready: https://$DEPLOYMENT_URL"
              echo "VERCEL_DEPLOYMENT_URL=https://$DEPLOYMENT_URL" >> $GITHUB_ENV
              break
            else
              echo "⏳ Deployment not ready yet. Waiting 10 seconds..."
              sleep 10
            fi
          done

          if [ -z "$DEPLOYMENT_URL" ]; then
            echo "❌ Timeout waiting for Vercel deployment after $MAX_ATTEMPTS attempts"
            exit 1
          fi

      - name: Create Synpress cache
        run: |
          xvfb-run bun run cache-e2e-wallet

      - name: Validate Base URL
        run: |
          if [ -z "$VERCEL_DEPLOYMENT_URL" ] && [ -z "${{ inputs.base_url }}" ]; then
            echo "❌ No base URL available. Either:"
            echo "1. Provide base_url input when triggering workflow"
            echo "2. Ensure Vercel deployment is ready (for pull requests)"
            exit 1
          fi
          echo "✅ Base URL validated"

      - name: Run tests
        run: |
          xvfb-run bun run test-e2e-tag ${{ inputs.tag || '@near-intents-wallet' }}
        env:
          NEXT_PUBLIC_BASE_URL: ${{ env.VERCEL_DEPLOYMENT_URL || inputs.base_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ inputs.tag || '@near-intents-wallet' }}
          path: my-report/
          retention-days: 5
