name: E2E UI automation tests worker

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      tag:
        description: "Provide tag to run tests by"
        required: true
        type: string
      base_url:
        description: "Base URL for the application (default: localhost:3000)"
        required: false
        type: string
        default: "http://localhost:3000"
      manual_trigger:
        required: false
        type: boolean
        default: true
    secrets:
      MM_SEED_PHRASE:
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: "Provide tag to run tests by"
        required: true
        type: choice
        options:
          - "@near-intents-wallet"
          - "@near-intents-wallet-swapping"
          - "@near-intents-wallet-otc"
          - "@near-intents-wallet-deposit"
          - "@near-intents-wallet-withdraw"
      base_url:
        description: "Base URL for the application (default: localhost:3000)"
        required: false
        type: string
        default: "http://localhost:3000"
      manual_trigger:
        description: "Set to true to manually trigger the workflow"
        required: false
        type: boolean
        default: false

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    # runs-on: ubuntu-8-core
    timeout-minutes: 240

    env:
      MM_SEED_PHRASE: ${{ secrets.MM_SEED_PHRASE }}
      NEXT_PUBLIC_BASE_URL: ${{ inputs.base_url || 'http://localhost:3000' }}
      # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      RUN_TAG: ${{ inputs.tag || '@near-intents-wallet' }}
      MANUAL_TRIGGER: ${{ inputs.manual_trigger }}
      EXTENSION_LOAD_TIMEOUT: 60000
      CHROME_ARGS: "--no-sandbox --disable-dev-shm-usage"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Jod

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install linux deps
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 2560x1440x24 -listen tcp -ac &
          fluxbox -display :0.0 &
        env:
          DISPLAY: :0.0

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright
        run: bunx playwright install

      - name: Cache Next.js build artifacts
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lockb') }}-

      - name: Build application
        if: ${{ inputs.base_url == 'http://localhost:3000' || inputs.base_url == '' }}
        run: bun run build

      - name: Start development server
        if: ${{ inputs.base_url == 'http://localhost:3000' || inputs.base_url == '' }}
        run: |
          bun start &
          sleep 10
          # Wait for server to be ready
          timeout 60 bash -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do sleep 1; done'

      - name: Create Synpress cache
        run: |
          xvfb-run bun run cache-e2e-wallet

      - name: Run tests
        run: |
          xvfb-run bun run test-e2e-tag ${{ inputs.tag || '@near-intents-wallet' }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ inputs.tag || '@near-intents-wallet' }}
          path: my-report/
          retention-days: 5
