name: Security Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security_analysis:
    name: Shared
    uses: aurora-is-near/.github/.github/workflows/security_analysis.yml@d8ed49075f1cef41d7326cf07982872c362a2bc6
    secrets: inherit
